# ROI in fractional coords (x_center, y_center, width, height)
roi: [0.5, 0.5, 0.4, 0.4]
target_fps: 60.0       # your converted video FPS
segment_seconds: 3.0   # window length for labels / features
overlap_seconds: 1.0
min_brightness: 5.0    # ignore too-dark frames
